### PR TITLE
Span compat

### PR DESCRIPTION
**Pull request by martijn00**
Add netstandard support for Span on: https://github.com/minio/minio-dotnet/pull/754

### CODE REVIEW

**Comment by ebozduman** [comment]
First, I see the following issue when I run functional tests against 4.8:
```$ dotnet run --project ./Minio.Functional.Tests/Minio.Functional.Tests.csproj
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj : error NU1605: Warning As Error: Detected package downgrade: System.ValueTuple from 4.5.0 to 4.4.0. Reference the package directly from the project to select a different version. 
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj : error NU1605:  Minio.Functional.Tests -> Minio -> System.Text.Json 7.0.2 -> System.ValueTuple (>= 4.5.0) 
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj : error NU1605:  Minio.Functional.Tests -> Minio -> System.ValueTuple (>= 4.4.0)
```
After fixing it by simply bumping up the version of `System.ValueTuple`  package to `4.5.0`, I see the following:
```
$ dotnet run --project ./Minio.Functional.Tests/Minio.Functional.Tests.csproj
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/RandomStreamGenerator.cs(28,27): error CS1503: Argument 1: cannot convert from 'System.Span<byte>' to 'byte[]' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(720,62): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(721,42): error CS1061: 'FileStream' does not contain a definition for 'DisposeAsync' and no accessible extension method 'DisposeAsync' accepting a first argument of type 'FileStream' could be found (are you missing a using directive or an assembly reference?) [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(804,62): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(805,42): error CS1061: 'FileStream' does not contain a definition for 'DisposeAsync' and no accessible extension method 'DisposeAsync' accepting a first argument of type 'FileStream' could be found (are you missing a using directive or an assembly reference?) [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(885,62): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(886,42): error CS1061: 'FileStream' does not contain a definition for 'DisposeAsync' and no accessible extension method 'DisposeAsync' accepting a first argument of type 'FileStream' could be found (are you missing a using directive or an assembly reference?) [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(926,33): error CS0117: 'File' does not contain a definition for 'ReadAllBytesAsync' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(960,33): error CS0117: 'File' does not contain a definition for 'ReadAllBytesAsync' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(1498,41): error CS0117: 'MD5' does not contain a definition for 'HashData' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(1500,38): error CS0117: 'MD5' does not contain a definition for 'HashData' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(2612,41): error CS1503: Argument 1: cannot convert from 'string' to 'char' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(2697,49): error CS0103: The name 'HttpUtility' does not exist in the current context [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4574,62): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4575,42): error CS1061: 'FileStream' does not contain a definition for 'DisposeAsync' and no accessible extension method 'DisposeAsync' accepting a first argument of type 'FileStream' could be found (are you missing a using directive or an assembly reference?) [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4717,28): error CS0117: 'File' does not contain a definition for 'WriteAllLinesAsync' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4750,66): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4751,46): error CS1061: 'FileStream' does not contain a definition for 'DisposeAsync' and no accessible extension method 'DisposeAsync' accepting a first argument of type 'FileStream' could be found (are you missing a using directive or an assembly reference?) [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4758,61): error CS0117: 'File' does not contain a definition for 'ReadAllTextAsync' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4810,35): error CS0117: 'File' does not contain a definition for 'OpenHandle' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4811,57): error CS1503: Argument 2: cannot convert from 'System.IO.FileAccess' to 'System.IO.FileMode' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]
/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs(4827,48): error CS1503: Argument 2: cannot convert from 'System.Threading.CancellationToken' to 'int' [/home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Minio.Functional.Tests.csproj]

The build failed. Fix the build errors and run again.
```
I started looking into these, but then I had to switch to another task. If you'd like I can send you the diffs of the files I've touched.

**Comment by martijn00** [comment]
@ebozduman Why would you switch that to 4.8? It is even on 6.0 on the older branches: https://github.com/minio/minio-dotnet/blob/4.0.7/Minio.Functional.Tests/Minio.Functional.Tests.csproj#L3

It never worked on net4.8. The library will be compatible with 4.8 this way, but the test are just an output, and the code itself should not be compatible.

**Comment by martijn00** [comment]
@ebozduman Anyways, i've added the support for net48 in the tests. Can you get the nuget release out please?

**Comment by ebozduman** [comment]
@martijn00,
.NET4.x was supposed to be tested and supported since from the first day. So, we need to fix any incompatibility issues, add required testing in CI process and fully support it.

Thank you for working on this task.

**Comment by martijn00** [comment]
@ebozduman I've just fixed the failing test

**Comment by ebozduman** [comment]
@martijn00

I will push some changes in a short while. These changes go on top of your PR, #757, and it completes the changes required to support older 4.x dotnet releases together with 6.0 and 7.0 dotnet releases we support. I ran all functional tests against all the supported releases, `4.7.2, 4.8, 4.8.1, 6.0, 7.0`, and they all passed successfully.

However, I expect the `dotnet regitlint` check to fail during the CI build process because of a bug in `JetBrains.ReSharper.Psi.ExtensionsAPI.Tree.ModificationUtil.DeleteChildRange`.
I am looking into it and I think there is a workaround to it.

I appreciate if you could review my changes in the meantime.

As soon as the lint check issue is resolved and the review is complete, we can merge PR#757 and start a new release.

**Comment by ebozduman** [comment]
@martijn00 ,

Please disregard the last 2 commits. It is my bad (I was sleep deprived). I'll fix it.

**Comment by martijn00** [comment]
@ebozduman hehe alright, I'll wait a bit then because you did some strange things in there. Also I want to say again, lets get a release out first and then follow up with more fixes and warning updates because this is getting way too big.

**Comment by ebozduman** [comment]
Yes @martijn00 ,
I agree.
I had to reverse some of your changes to make the code work for 4.x and for core releases.
We can make the code better as soon as a new Minio package is built and released.

**Comment by martijn00** [comment]
@ebozduman what are you doing with those commits? Please revert because it is not correct. Let me know what you want so I can have a look if changes need to be made.

**Comment by ebozduman** [comment]
You're right. I'll clean it up.

**Comment by ebozduman** [comment]
Done. My recent commit is removed.
 
As soon as, the build testing is a PASS, we can merge the PR.

Could you please look into the build lint failures?
When the lint issues are addressed, there will be 2 more little fixes we'll need:

1- Func. test `ObjectLockConfigurationAsync_Test1`  fails 
```
System.InvalidOperationException: There was an error reflecting type
'Minio.DataModel.Tags.Tagging'.
 ---> System.NotSupportedException: Cannot serialize member
Minio.DataModel.Tags.Tagging.Tags of type
System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib,
Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String,
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e]], because it implements
 IDictionary.
:
:
```

2- Mint.Logger.Log() function escapes some chars, special chars if any appears in the object name, function or in any other string in the log message. 
```
{"name":"minio-dotnet : CopyObject_Test4", 
"function":"Task\u003CCopyObjectResult\u003E 
CopyObjectAsync(CopyObjectArgs args, 
CancellationToken cancellationToken = default(CancellationToken))",
"args":{"bucketName":"minio-dotnet-example-caeox1ekrstju5b",
"objectName":"d%a\u002B#c\u0026caa",
"destBucketName":"minio-dotnet-example-qsokc6g6es725dj",
"data":"1KB","size":"1KB"},
"duration":73,"status":"PASS"}
```

  We need to turn the escaping off as they are just log messages.

**Comment by martijn00** [comment]
@ebozduman I've done all of those things now. Can you have a look and merge?

**Comment by martijn00** [comment]
@ebozduman Can you try again with the last commit?

**Comment by martijn00** [comment]
@ebozduman finally a green check! Lets merge!

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by martijn00** [comment]
@ebozduman Can you merge? I will follow up with some more warning cleanup afterwards.

**Comment by martijn00** [comment]
@ebozduman fixed the merge conflicts now. Can you merge the PR?

**Comment by martijn00** [comment]
@ebozduman thanks for merging! When do you expect to get a new nuget release published?

**Comment by ebozduman** [comment]
We'll try to do it this week.
