### PR TITLE
fix wrong MinIO Client Example example in README

### PR DESCRIPTION
**Pull request by lag945**
[Compiler Error CS0246](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246?f1url=%3FappId%3Droslyn%26k%3Dk(CS0246)) The type or namespace name 'type/namespace' could not be found (are you missing a using directive or an assembly reference?)
We can declare bucket with 'var'  or add 'using Minio.DataModel'.

### CODE REVIEW

**Comment by ebozduman** [comment]
@lag945 

The build tests fail due to an issue fixed by PR #693 and it hasn't been merged yet.
As soon as PR#693 is merged, you just need to sync with master.

**Review by ebozduman — APPROVED** [review]
LGTM

**Comment by lag945** [comment]
> @lag945
> 
> The build tests fail due to an issue fixed by PR #693 and it hasn't been merged yet. As soon as PR#693 is merged, you just need to sync with master.

@ebozduman Some checks were not successful, I don't understand how to "sync with master"? I need more  detail instructions, please.

**Comment by ebozduman** [comment]
@lag945 

I've spent some time to understand the issue and I could not find anything abnormal as the failing test does not seem to be doing anything special or different than before.
We may dig into more, if the same test continues to fail in a separate issue.
Rerunning the test did not hit any problem and your fix is now ready to be merged.
